[package]
name = "db-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "*"
prost = "0.14"
tonic-prost = "*"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
bincode = "2.0.1"

[build-dependencies]
tonic-prost-build = "*"
